### ISSUE TITLE
why does cp-scenario for scenario routekaart Groningen result in errors for some datasets?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etm-tools#5]
My aim is to create scenarios for ~100 neighbourhoods in Groningen based on an existing scenario (beta 922316).

I tried this for the first ~20 neighbourhoods (alphabetically).

snippet of results:
![image](https://user-images.githubusercontent.com/19907658/44714844-9bd50980-aab6-11e8-9116-ef3623085c6d.png)

I understand where the bounded errors come from, number of old houses cannot be greater than present value.

Some scenarios give an error which I do not understand.

### Example BU00090005_achter-thesinge_en_bovenrijge

cp-scenario for an empty scenario works fine:
bin/cp-scenario beta 912925 --dataset BU00090005_achter-thesinge_en_bovenrijge
![image](https://user-images.githubusercontent.com/19907658/44715396-ffac0200-aab7-11e8-9126-6152e9a9232e.png)

cp-scenario for beta: 922316 results in errors that I do not understand
bin/cp-scenario beta 922316 --dataset BU00090005_achter-thesinge_en_bovenrijge

Other examples of datasets that give an error are: BU00090101_winneweer_gedeeltelijk, BU00140108_stadspark and BU00140200_oranjebuurt.

@antw can you explain what is going wrong here?

**Comment by antw** [comment]
I've narrowed it down to the households_number_of_new_houses input. It [sets the demand for cooling and heating](https://github.com/quintel/etsource/blob/d6ea21de9d7a61fce2b12e8a69c16d241ccc3439/inputs/demand/households/households_misc/households_number_of_new_houses.ad#L31-L32) like so:

```ruby
UPDATE_WITH_FACTOR(
  L(households_new_houses_useful_demand_for_heating),
  preset_demand,
  USER_INPUT() * 1_000_000 / QUERY_PRESENT(-> { AREA(number_of_new_residences) })
),
UPDATE_WITH_FACTOR(
  L(households_new_houses_useful_demand_for_cooling),
  preset_demand,
  USER_INPUT() * 1_000_000 / QUERY_PRESENT(-> { AREA(number_of_new_residences) })
)
```

The problem is that this part: `QUERY_PRESENT(-> { AREA(number_of_new_residences) }`. These regions have zero residences in the present, resulting in a division-by-zero when setting the demand.

The best solution is to fix this in the query, perhaps by allowing `DIVIDE` to detect division-by-zero, but ideally I'd like to get everyone's feedback before making that change.

A simple *short-term* solution would be to give each of these datasets a single new household; the input should run fine as long as that attribute is non-zero.

**Comment by DorinevanderVlies** [comment]
> A simple short-term solution would be to give each of these datasets a single new household; the input should run fine as long as that attribute is non-zero.

I will implement this short-term solution for now.

> The best solution is to fix this in the query, perhaps by allowing DIVIDE to detect division-by-zero, but ideally I'd like to get everyone's feedback before making that change.

Would it be possible to use `UPDATE` instead of `UPDATE_WITH_FACTOR`?

including @michieldenhaan

**Comment by michieldenhaan** [comment]
Not so surprisingly, when changing the number of ``residences built after 1991`` in ETModel from 0 to some positive number for ``BU00090005_achter-thesinge_en_bovenrijge`` nothing happens and the console shows an error (see below).

> The best solution is to fix this in the query, perhaps by allowing DIVIDE to detect division-by-zero, but ideally I'd like to get everyone's feedback before making that change.

I'm happy with that! Ideally it should be possible to build 'new houses' regardless of the present number of new houses. However, we are going to revamp this part of the model soon anyway, so I guess it's not worth it to spend too much time on this. 



![energy transition model - your free independent comprehensive fact-based scenario builder httpsbeta-pro energytransiti 2018-08-28 15-41-41 1](https://user-images.githubusercontent.com/32056448/44726875-faab7a80-aad8-11e8-9f76-91bb7acda892.png)

**Comment by DorinevanderVlies** [comment]
Closing this issue as the problem described here will be solve in the heat improvement project
